# teams-dev-samples
# Author: Hugo Bernier, updates by Bob German
#
#region Sample entry (install region folding for VS Code add-in to make regions collapsable)
#
# Each sample has an entry as show below:
# 
#    - name: some-unique-name
#      title: 
#      type: apptemplate, barebones, demo, solution
#      features: bot, connector, meetings, msgext, tab, taskmodule, webhook
#      source: appTemplate, botBuilder, msftTeams, officeDev, pnp
#      summary: 
#      thumbnail: https://github.com/OfficeDev/microsoft-teams-apps-attendance/wiki/Images/Attendance_Readme_01.png
#      url: https://github.com/OfficeDev/microsoft-teams-apps-attendance
#      author: Microsoft
#      client_language: typescript, javascript, powerapps
#      client_platform: spa, spfx, mgt, powerapps, netcore, sharepoint
#      client_ui: react, angularjs, angular, knockout, jquery, vuejs
#      server_language: csharp, typescript, javascript, python, java, powerautomate
#      server_platform: netcore, netframework, express, restify, powerautomate, requests
#      bot_framework: bot3, bot4beta, bot40, bot46
#      modifiedtext: May 14, 2020
#      modified: 2020-05-14
#
#endregion

#region MKDocs App settings
site_name: Microsoft Teams Development Samples
plugins:
    - search
    - macros
    - markdownextradata
nav:
  - Samples:
    - By Type: index.md
    - By Feature: samples/features.md
    - By Source: samples/source.md
    - CLIENT SIDE CODE: samples/client_language.md
    - By Client Language: samples/client_language.md
    - By Client Platform: samples/client_platform.md
    - By Client UI Framework: samples/client_ui.md
    - SERVER CODE: samples/bot_framework.md
    - By Bot Framework Version: samples/bot_framework.md
    - By Server Language: samples/server_language.md
    - By Server Platform: samples/server_platform.md
  - Getting Started:
    - Using the Samples: gettingstarted/index.md
  - Contributing:
    - Contribution Guide: contributing/index.md
theme:
  name: 'material'
  custom_dir: 'custom_theme'
  palette:
    primary: 'pnp'
    accent: 'indigo'
  logo: 'img/pnp-samples-white.svg'
  feature:
    tabs: true
extra_css:
  - 'css/site.css'
  - 'css/extra.css'
  - 'css/filter.css'
  - 'https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.0.0/css/fabric.min.css'
extra_javascript:
  - 'https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js'
  - 'https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js'
  - 'javascript/isotope.pkgd.min.js'
  - 'javascript/loadsamples.js'
  - 'javascript/filtersamples.js'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  telemetry: 'telemetry.sharepointpnp.com/teams-dev-samples'
  twitter_site: '@m365pnp'
  media_url: https://pnp.github.io/teams-dev-samples/img/pnp-samples-white.png
  twitter_media_url: https://pnp.github.io/teams-dev-samples/img/pnp-samples-logo-twitter.png
  media_alt: Patterns and Practices Samples
  site_search_url: https://pnp.github.io/teams-dev-samples/?query=
  version: '1.0.0-0'
  social:
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/m365pnp'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/playlist?list=PLR9nK3mnD-OXgMjDBdjWUTRia89oixBhx'
    - icon: 'fontawesome/solid/link'
      link: 'https://aka.ms/m365pnp'
repo_url: https://github.com/pnp/teams-dev-samples
edit_uri: tree/Docs/docs
site_url: https://pnp.github.io/teams-dev-samples/
site_description: A gallery of Microsoft Teams samples created by the community
#endregion

# Uncomment during testing if you need to change the default web server settings

#dev_addr: '192.168.24.52:8000'  # BG nubuntu
# dev_addr: '127.0.0.1:443'